# Generated by Django 5.0.8 on 2024-08-28 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(
                default="Ok",
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$", "Enter a valid 11-digit mobile number."
                    )
                ],
            ),
        ),
    ]
