# Generated by Django 5.0.8 on 2024-08-28 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_mobile_number"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$", "Enter a valid 11-digit mobile number."
                    )
                ],
            ),
        ),
    ]
